/**
 * Generate gen/ts/{types,zod,constants,angles,index}.ts.
 *
 * Everything written here is committed and diffed by CI (`git diff --exit-code
 * gen/`), so the output must be a pure function of schemas/, constants/ and
 * angles/ — no timestamps, no host paths, no iteration over an unordered set.
 *
 * ## The one thing the off-the-shelf generators get wrong
 *
 * Both envelope schemas select their payload with `allOf: [{if: {type: const
 * X}, then: {payload: $ref}}]`. `json-schema-to-zod` renders that as
 * `z.intersection(z.any(), z.any())` — a validator that accepts a heartbeat
 * payload inside an `inclination` frame and reports success. A generated
 * validator that silently does not validate is worse than none, so envelopes
 * are emitted here as an explicit `z.discriminatedUnion` built from the same
 * if/then table. Same for the TypeScript side, where the plain compile gives
 * `payload: {}`.
 *
 * If a future schema uses a conditional shape this does not recognise, the
 * generator throws rather than emitting the weak version.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { compile } from 'json-schema-to-typescript';
import { jsonSchemaToZod } from 'json-schema-to-zod';
import { bundleAll, baseOf, discriminatorTable } from './bundle.mjs';

const ROOT = new URL('..', import.meta.url).pathname.replace(/\/$/, '');
const OUT = join(ROOT, 'gen', 'ts');

const BANNER = (source) => `/**
 * AUTO-GENERATED BY tools/gen.sh. DO NOT EDIT.
 *
 * Source: ${source}
 * Regenerate with \`tools/gen.sh\`; CI fails on any drift.
 */
`;

/** `device-envelope` → `DeviceEnvelope`. */
function pascal(slug) {
    return slug.replace(/(^|[-_])(\w)/g, (_, __, ch) => ch.toUpperCase());
}

/** Descriptions are JSDoc on the type side and dead weight on the validator
 *  side, where they would triple the file and repeat once per union member. */
function stripDescriptions(node) {
    if (Array.isArray(node)) return node.map(stripDescriptions);
    if (node === null || typeof node !== 'object') return node;
    const out = {};
    for (const [key, value] of Object.entries(node)) {
        if (key === 'description' || key === '$comment' || key === 'title') continue;
        out[key] = stripDescriptions(value);
    }
    return out;
}

async function compileType(bundled, name) {
    // `$id` and `title` both outrank the name argument in
    // json-schema-to-typescript, and a URN `$id` produces an unusable name. Drop
    // both so the exported name is a pure function of the file path.
    const { $id, title, ...body } = structuredClone(bundled);
    const compiled = await compile(body, name, {
        bannerComment: '',
        additionalProperties: false,
        declareExternallyReferenced: true,
        enableConstEnums: false,
        style: { singleQuote: true, tabWidth: 4, printWidth: 100 },
    });
    return compiled.trim();
}

async function writeTypes(bundles, idToSlug) {
    const parts = [BANNER('every schema under schemas/ (json-schema-to-typescript)')];
    for (const { slug, path, schema, bundled } of bundles) {
        const table = discriminatorTable(schema, idToSlug, path);
        const name = pascal(slug);
        if (table === null) {
            parts.push(await compileType(bundled, name), '');
            continue;
        }
        // The envelope's shared fields, then the union that actually pairs a
        // `type` with its payload.
        parts.push(await compileType(baseOf(bundled), `${name}Base`), '');
        const members = table.branches.map(
            ({ value, slug: payloadSlug }) =>
                `    | (Omit<${name}Base, '${table.discriminator}' | 'payload'> & {\n` +
                `          ${table.discriminator}: '${value}';\n` +
                `          payload: ${pascal(payloadSlug)};\n` +
                `      })`
        );
        parts.push(
            `/**\n * ${schema.title ?? name}.\n *\n` +
                ` * Discriminated on \`${table.discriminator}\`, so narrowing a frame narrows its\n` +
                ` * payload with it. Reconstructed from the schema's \`allOf\` if/then table by\n` +
                ` * tools/gen-ts.mjs, which json-schema-to-typescript renders as \`payload: {}\`.\n */`,
            `export type ${name} =`,
            `${members.join('\n')};`,
            ''
        );
    }
    writeFileSync(join(OUT, 'types.ts'), `${parts.join('\n')}\n`);
}

function zodFor(schema) {
    return jsonSchemaToZod(stripDescriptions(structuredClone(schema)), { module: 'none', type: false });
}

function writeZod(bundles, idToSlug) {
    const parts = [
        BANNER('every schema under schemas/ (json-schema-to-zod)'),
        '/**',
        ' * Runtime validators. OPTIONAL: `zod` is a peer dependency and nothing in',
        " * `needle-protocol`'s default entry point imports this module.",
        ' *',
        ' * The 60 Hz angle-frame parse path in needle-simulator is hand-written on',
        ' * purpose and must stay that way — a schema library in that loop is a',
        ' * dependency in the hot path. Use these where the cost is free: tests,',
        ' * fixtures, capture validation, and the first frame of a new connection.',
        ' */',
        "import { z } from 'zod';",
        '',
    ];
    // Payload schemas first: an envelope's union refers to them by name.
    const deferred = [];
    for (const bundle of bundles) {
        const table = discriminatorTable(bundle.schema, idToSlug, bundle.path);
        if (table === null) {
            parts.push(`/** \`${bundle.path}\` */`, `export const ${pascal(bundle.slug)}Schema = ${zodFor(bundle.bundled)};`, '');
        } else {
            deferred.push({ bundle, table });
        }
    }
    for (const { bundle, table } of deferred) {
        const name = pascal(bundle.slug);
        const members = table.branches.map(
            ({ value, slug }) =>
                `    ${name}Base.extend({ ${table.discriminator}: z.literal('${value}'), payload: ${pascal(slug)}Schema }),`
        );
        parts.push(
            `/** Shared fields of \`${bundle.path}\`, before the payload is pinned down. */`,
            `const ${name}Base = ${zodFor(baseOf(bundle.bundled))};`,
            '',
            `/**\n * \`${bundle.path}\`\n *\n` +
                ` * A discriminated union rather than the schema's literal \`allOf\`: json-schema-to-zod\n` +
                ` * renders an if/then table as \`z.intersection(z.any(), z.any())\`, which accepts any\n` +
                ` * payload on any \`${table.discriminator}\` and reports success.\n */`,
            `export const ${name}Schema = z.discriminatedUnion('${table.discriminator}', [`,
            members.join('\n'),
            ']);',
            ''
        );
    }
    writeFileSync(join(OUT, 'zod.ts'), `${parts.join('\n')}\n`);
}

function wrap(text, width) {
    const words = text.split(/\s+/);
    const lines = [];
    let line = '';
    for (const word of words) {
        if (line.length === 0) line = word;
        else if (line.length + 1 + word.length <= width) line += ` ${word}`;
        else {
            lines.push(line);
            line = word;
        }
    }
    if (line) lines.push(line);
    return lines;
}

function writeConstants(constants) {
    const parts = [BANNER('constants/constants.json')];
    for (const [name, spec] of Object.entries(constants.constants)) {
        parts.push('/**');
        for (const line of wrap(spec.description, 74)) parts.push(` * ${line}`);
        if (spec.sources?.length) {
            parts.push(' *', ' * Mirrors:');
            for (const source of spec.sources) parts.push(` * - ${source}`);
        }
        parts.push(' */');
        parts.push(
            spec.type === 'integer[]'
                ? `export const ${name}: readonly number[] = ${JSON.stringify(spec.value)} as const;`
                : `export const ${name} = ${JSON.stringify(spec.value)} as const;`
        );
        parts.push('');
    }
    writeFileSync(join(OUT, 'constants.ts'), `${parts.join('\n')}\n`);
}

function writeAngles() {
    const source = readFileSync(join(ROOT, 'angles', 'ts', 'src', 'index.ts'), 'utf8');
    writeFileSync(
        join(OUT, 'angles.ts'),
        `${BANNER('angles/ts/src/index.ts (copied verbatim)')}\n${source}`
    );
}

/**
 * The exported names of the angles module, split into values and types.
 *
 * Read out of the source rather than listed by hand, because this list feeds
 * the package's public surface and a hand-kept copy would silently stop
 * exporting whatever was added last.
 */
function angleExports(source) {
    const values = [];
    const types = [];
    const pattern = /^export (const|function|interface|type) ([A-Za-z0-9_]+)/gm;
    for (const [, kind, name] of source.matchAll(pattern)) {
        (kind === 'interface' || kind === 'type' ? types : values).push(name);
    }
    if (values.length === 0) throw new Error('angles module exports no values; the parser is wrong.');
    return { values, types };
}

function writeIndex(constants) {
    const source = readFileSync(join(ROOT, 'angles', 'ts', 'src', 'index.ts'), 'utf8');
    const { values, types } = angleExports(source);
    // A constant that lives in constants/constants.json is re-exported from
    // there and from nowhere else. The angles module declares its own copy so
    // it can stay dependency-free; the suites pin the two to the same value, so
    // which one the package hands out cannot matter — but exporting both would
    // be an ambiguous re-export, and picking the single source of truth is the
    // answer that stays right when a value changes.
    const shared = new Set(Object.keys(constants.constants));
    const fromAngles = values.filter((name) => !shared.has(name)).sort();
    const shadowed = values.filter((name) => shared.has(name)).sort();

    const lines = [
        `${BANNER('tools/gen-ts.mjs')}`,
        '/**',
        ' * The whole package, minus `./zod`.',
        ' *',
        ' * `zod.ts` is deliberately NOT re-exported here: importing this module must',
        ' * never pull `zod` into a bundle, because the angle-frame parse path runs at',
        ' * 60 Hz and needle-guide reads these constants in Electron main process at',
        ' * startup. Reach for the validators explicitly, via `needle-protocol/zod`.',
        ' */',
        "export * from './types.js';",
        "export * from './constants.js';",
    ];
    if (shadowed.length > 0) {
        lines.push(
            `// Also declared by the angles module, and re-exported above from`,
            `// constants/constants.json, which is the single source of truth for it:`,
            ...shadowed.map((name) => `//   ${name}`)
        );
    }
    lines.push(`export {\n${fromAngles.map((n) => `    ${n},`).join('\n')}\n} from './angles.js';`);
    if (types.length > 0) {
        lines.push(
            `export type {\n${[...types].sort().map((n) => `    ${n},`).join('\n')}\n} from './angles.js';`
        );
    }
    writeFileSync(join(OUT, 'index.ts'), `${lines.join('\n')}\n`);
}

async function main() {
    mkdirSync(OUT, { recursive: true });
    const { bundles, idToSlug } = bundleAll();
    const constants = JSON.parse(readFileSync(join(ROOT, 'constants', 'constants.json'), 'utf8'));
    await writeTypes(bundles, idToSlug);
    writeZod(bundles, idToSlug);
    writeConstants(constants);
    writeAngles();
    writeIndex(constants);
    console.log(`[gen-ts] gen/ts/{types,zod,constants,angles,index}.ts from ${bundles.length} schema(s)`);
}

await main();
