#!/usr/bin/env python3
"""Generate gen/py/needle_protocol/{models,constants,angles,__init__}.py.

Everything written here is committed and diffed by CI (``git diff --exit-code
gen/``), so the output must be a pure function of ``schemas/``,
``constants/constants.json`` and ``angles/py/`` -- no timestamps, no host paths,
no iteration over an unordered set.

Two things this does that a bare ``datamodel-codegen`` invocation does not:

1. **Stable nested class names.** Left alone, the generator names nested objects
   and enums ``Link``, ``Link1``, ``Type``, ``Type1`` -- numbered by the order it
   happens to meet them. Adding a schema whose name sorts earlier would then
   silently rename a class a consumer imports. Every nested object and enum is
   given an explicit ``title`` derived from its own path, so the name depends on
   where it lives and nothing else.

2. **Envelopes stay discriminated.** The ``allOf`` if/then payload table is
   rendered as ``payload: dict[str, Any]``, i.e. a model that accepts a
   heartbeat payload inside an ``inclination`` frame. The base is generated as
   ``<Name>Base`` and the tagged union is appended, mirroring gen/ts.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUNDLED = ROOT / "build" / "bundled"
OUT = ROOT / "gen" / "py" / "needle_protocol"

# The name of the combined input, which datamodel-codegen stamps into its header
# comment. A path would make the output depend on where the repo is checked out.
COMBINED_NAME = "needle-protocol.schema.json"

BANNER = """\
# AUTO-GENERATED BY tools/gen.sh. DO NOT EDIT.
#
# Source: {source}
# Regenerate with `tools/gen.sh`; CI fails on any drift.
"""

# datamodel-codegen emits this for the combined document's own (empty) root. It
# is an artefact of having to hand the tool ONE file, carries no contract, and
# is removed rather than exported. Matched exactly: if the tool's output shape
# changes, this script fails instead of leaving a stray class behind.
ROOT_CLASS = """class NeedleProtocol(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )


"""


def pascal(slug: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[-_]", slug))


def title_nested(node: object, prefix: str) -> None:
    """Give every nested object/enum an explicit, path-derived ``title``.

    Only nested ones: the top level already carries the contract's own name.
    """
    if isinstance(node, list):
        for item in node:
            title_nested(item, prefix)
        return
    if not isinstance(node, dict):
        return
    for key, value in node.items():
        if key == "properties" and isinstance(value, dict):
            for prop, sub in value.items():
                if isinstance(sub, dict) and ("properties" in sub or "enum" in sub):
                    sub.setdefault("title", prefix + pascal(prop))
                title_nested(sub, prefix + pascal(prop))
        else:
            title_nested(value, prefix)


def build_combined(contracts: list[dict]) -> dict:
    """One document holding every contract under ``$defs``.

    datamodel-codegen refuses to merge a directory of schemas into a single
    module, and a module per schema would give three copies of the ``link``
    object with three different names. So the contracts are handed over as one
    document; the ``$defs`` key becomes the class name.
    """
    defs: dict[str, dict] = {}
    for contract in contracts:
        schema = json.loads((BUNDLED / f"{contract['slug']}.json").read_text())
        for dropped in ("$id", "$schema", "title"):
            schema.pop(dropped, None)
        name = pascal(contract["slug"])
        if contract["table"] is not None:
            # The tagged union is appended below; the generator only produces
            # the fields every variant shares.
            schema.pop("allOf", None)
            name += "Base"
        title_nested(schema, name)
        defs[name] = schema
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "NeedleProtocol",
        "type": "object",
        "additionalProperties": False,
        "properties": {},
        "$defs": defs,
    }


def render_unions(contracts: list[dict]) -> str:
    """Tagged unions for the envelope contracts, mirroring gen/ts/zod.ts."""
    blocks: list[str] = []
    aliases: list[str] = []
    for contract in contracts:
        table = contract["table"]
        if table is None:
            continue
        name = pascal(contract["slug"])
        disc = table["discriminator"]
        variants = []
        for branch in table["branches"]:
            variant = f"{name}{pascal(branch['value'])}"
            variants.append(variant)
            # Properties the schema's `then` pins to a literal alongside the
            # payload -- the plan-channel envelope binds `kind` to `type` this
            # way. Dropping them here would leave a constraint the schema states
            # and the model does not enforce.
            pinned = "".join(
                f"    {key}: Literal[{value!r}]\n"
                for key, value in branch.get("consts", {}).items()
            )
            blocks.append(
                f'class {variant}({name}Base):\n'
                f'    """`{contract["path"]}` with `{disc} == "{branch["value"]}"`."""\n\n'
                f"    {disc}: Literal[{branch['value']!r}]\n"
                f"{pinned}"
                f"    payload: {pascal(branch['slug'])}\n"
            )
        union = " | ".join(variants) if len(variants) > 1 else variants[0]
        aliases.append(
            f"#: `{contract['path']}`, tagged on `{disc}` so that narrowing the frame\n"
            f"#: narrows its payload. The schema's `allOf` if/then table renders as\n"
            f"#: `payload: dict[str, Any]` on its own -- a model that would accept any\n"
            f"#: payload under any `{disc}` and report success.\n"
            f'{name} = Annotated[\n    {union},\n    Field(discriminator={disc!r}),\n]\n'
        )
    if not blocks:
        return ""
    # The imports are restated rather than spliced into the generator's own
    # import block: which names datamodel-codegen happens to import varies with
    # the schemas, and a splice that silently no-ops would produce a file that
    # fails at import time instead of at generation time.
    return (
        "\n# ---------------------------------------------------------------------------\n"
        "# Tagged unions, appended by tools/gen-py.py from the schemas' if/then tables.\n"
        "# ---------------------------------------------------------------------------\n"
        "from typing import Annotated  # noqa: E402,F811\n"
        "\n"
        "from pydantic import Field  # noqa: E402,F811\n\n"
        + "\n\n".join(blocks)
        + "\n\n"
        + "\n\n".join(aliases)
    )


def wrap(text: str, width: int) -> list[str]:
    words = text.split()
    lines: list[str] = []
    line = ""
    for word in words:
        if not line:
            line = word
        elif len(line) + 1 + len(word) <= width:
            line += f" {word}"
        else:
            lines.append(line)
            line = word
    if line:
        lines.append(line)
    return lines


def py_literal(spec: dict) -> str:
    if spec["type"] == "integer[]":
        return "(" + ", ".join(str(v) for v in spec["value"]) + ")"
    return repr(spec["value"])


def py_annotation(spec: dict) -> str:
    return {
        "integer": "int",
        "number": "float",
        "string": "str",
        "integer[]": "tuple[int, ...]",
    }[spec["type"]]


def write_constants(constants: dict) -> None:
    parts = [
        BANNER.format(source="constants/constants.json"),
        '"""Shared literals. Standard library only: importing this costs nothing."""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Final",
        "",
        "__all__ = [",
    ]
    parts += [f'    "{name}",' for name in sorted(constants["constants"])]
    parts += ["]", ""]
    for name, spec in constants["constants"].items():
        parts.append("")
        for line in wrap(spec["description"], 74):
            parts.append(f"#: {line}")
        if spec.get("sources"):
            parts.append("#:")
            parts.append("#: Mirrors:")
            for source in spec["sources"]:
                parts.append(f"#: - {source}")
        parts.append(f"{name}: Final[{py_annotation(spec)}] = {py_literal(spec)}")
    return OUT.joinpath("constants.py").write_text("\n".join(parts) + "\n")


def write_angles() -> None:
    source = (ROOT / "angles" / "py" / "needle_protocol" / "angles.py").read_text()
    OUT.joinpath("angles.py").write_text(
        BANNER.format(source="angles/py/needle_protocol/angles.py (copied verbatim)") + "\n" + source
    )


def write_init() -> None:
    OUT.joinpath("__init__.py").write_text(
        BANNER.format(source="tools/gen-py.py")
        + '''
"""Shared wire contracts, angle conventions and constants.

`constants` and `angles` are re-exported here and are standard library only, so
importing this package is free. `models` is NOT imported: it needs pydantic,
which is the optional `models` extra, and a consumer that only wants the shared
literals (the Jetson appliance, the firmware tooling) must not be made to
install it. Reach for the models explicitly:

    from needle_protocol.models import DeviceEnvelope
"""

from needle_protocol.angles import *  # noqa: F401,F403
from needle_protocol.angles import __all__ as _angles_all
from needle_protocol.constants import *  # noqa: F401,F403
from needle_protocol.constants import __all__ as _constants_all

__all__ = [*_constants_all, *_angles_all]
'''
    )


def main() -> int:
    contracts = json.loads((ROOT / "build" / "contracts.json").read_text())
    OUT.mkdir(parents=True, exist_ok=True)

    combined_path = ROOT / "build" / COMBINED_NAME
    combined_path.write_text(json.dumps(build_combined(contracts), indent=2) + "\n")

    models_tmp = ROOT / "build" / "models.py"
    models_tmp.unlink(missing_ok=True)
    subprocess.run(
        [
            "datamodel-codegen",
            "--input", str(combined_path),
            "--input-file-type", "jsonschema",
            "--output", str(models_tmp),
            "--output-model-type", "pydantic_v2.BaseModel",
            "--target-python-version", "3.10",
            "--use-title-as-name",
            "--use-standard-collections",
            "--disable-timestamp",
            # Explicit, because the default set is on its way to becoming
            # opt-in; leaving it implicit would change the committed output on a
            # dependency bump and turn an unrelated PR red.
            "--formatters", "black", "isort",
        ],
        check=True,
        cwd=combined_path.parent,
    )

    body = models_tmp.read_text()
    if ROOT_CLASS not in body:
        print(
            "[gen-py] datamodel-codegen no longer emits the combined document's root class in the "
            "expected shape. Update ROOT_CLASS in tools/gen-py.py to match, rather than leaving an "
            "unexplained model in the published package.",
            file=sys.stderr,
        )
        return 1
    body = body.replace(ROOT_CLASS, "", 1)

    unions = render_unions(contracts)
    OUT.joinpath("models.py").write_text(
        BANNER.format(source="every schema under schemas/ (datamodel-code-generator)")
        + "\n"
        + body.rstrip("\n")
        + "\n"
        + unions
    )

    write_constants(json.loads((ROOT / "constants" / "constants.json").read_text()))
    write_angles()
    write_init()
    print(f"[gen-py] gen/py/needle_protocol/*.py from {len(contracts)} schema(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
